name: Deploy MBTI-App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Ensure bootstrap/cache directory exists
        run: mkdir -p bootstrap/cache

      - name: Set permissions for bootstrap/cache
        run: chmod -R 775 bootstrap/cache

      - name: Export environment variables
        env:
          APP_NAME: MBTI-App
          APP_ENV: production
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_DEBUG: false
          APP_TIMEZONE: Asia/Tokyo
          APP_URL: http://35.74.145.129/
          APP_LOCALE: ja
          APP_FALLBACK_LOCALE: en
          APP_FAKER_LOCALE: ja_JP
          APP_MAINTENANCE_DRIVER: file
          BCRYPT_ROUNDS: 12
          LOG_CHANNEL: stack
          LOG_STACK: single
          LOG_DEPRECATIONS_CHANNEL: null
          LOG_LEVEL: error
          SUPABASE_URL: https://lvrrijkuanvcqojypjvl.supabase.co
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          BROADCAST_CONNECTION: log
          FILESYSTEM_DISK: local
          QUEUE_CONNECTION: database
          CACHE_STORE: database
          MAIL_MAILER: log
          MAIL_HOST: 127.0.0.1
          MAIL_PORT: 2525
          MAIL_USERNAME: null
          MAIL_PASSWORD: null
          MAIL_ENCRYPTION: null
          MAIL_FROM_ADDRESS: "no-reply@example.com"
          MAIL_FROM_NAME: "No Reply"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
          AWS_BUCKET: mbti-app
          AWS_USE_PATH_STYLE_ENDPOINT: false
          VITE_APP_NAME: MBTI-App
        run: |
          export APP_KEY=${APP_KEY}
          export SUPABASE_API_KEY=${SUPABASE_API_KEY}
          export SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
          export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Create CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
            --application-name MBTI-App \
            --deployment-group-name MBTI-Deploy-Group \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
