name: Deploy MBTI-App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Ensure bootstrap/cache directory exists
        run: mkdir -p bootstrap/cache

      - name: Set permissions for bootstrap/cache
        run: chmod -R 775 bootstrap/cache

      - name: Create ENV file
        run: |
          echo "${{ secrets.PROD_ENV }}" > .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Create CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
            --application-name MBTI-App \
            --deployment-group-name production \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
